import type { Rule } from "../../core/rule.js";
import {
  dataRegisterOperand,
  immediateExpressionOperand,
  instructionSize,
  isInstruction,
} from "../../util/ast.js";
import {
  divideRecipes,
  type DivideRecipe,
} from "./generated/divide-recipes.js";
import { changedFlagsApplicability } from "./helpers.js";

const render = (recipe: DivideRecipe, d: string, scratch?: string) =>
  recipe.code.replaceAll("%d", d).replaceAll("%s", scratch ?? "");

const oneLine = (code: string) => code.replaceAll("\n", " ; ");

/** MULU, SWAP and MOVE leave X alone; shifts and adds set it. */
const writesX = (recipe: DivideRecipe) =>
  recipe.code
    .split("\n")
    .some((line) => /^(lsr|add|addx|sub|subx)\b/.test(line));

/**
 * DIVU.W by a constant costs 144 cycles at worst. Multiplying by a reciprocal
 * (or, for a small dividend, a few shifts and adds) is much cheaper, but it
 * only gives the quotient, and only for dividends in the range it was built
 * for. Neither can be proven from the code alone, so the range is the user's to
 * confirm; the remainder and the flags are checked.
 */
export const divuWordByConstant: Rule = {
  meta: {
    obfuscated: true,
    id: "optimization/divu-word-by-constant",
    category: "optimization",
    defaultSeverity: "suggestion",
    description:
      "Replace unsigned word division by a constant with a multiply by its reciprocal when only the quotient of a small dividend is needed",
    tags: [
      "divide",
      "multiply",
      "reciprocal",
      "generated",
      "remainder",
      "review",
      "68000",
    ],
    serves: "speed",
    docs: {
      source:
        "Generated by scripts/generate-divide-recipes.mjs (reciprocal multiplication, and shift/add sequences for small dividends)",
      note: "Only the quotient is produced, so this needs the remainder in the upper word of the register to be unused, and every recipe is exact only below a stated dividend. The register analysis cannot prove the range, so this is always a conditional suggestion.",
      example: {
        source: "\tdivu.w #10,d0\n\tmove.w d0,d2\n\tmoveq #0,d0\n\trts",
      },
    },
  },

  checkLine(ctx, line, index) {
    if (
      !ctx.config.processors.every((cpu) => cpu === "mc68000") ||
      !isInstruction(line, "divu") ||
      instructionSize(line) !== "w"
    )
      return;
    const expr = immediateExpressionOperand(line, 0);
    const dest = dataRegisterOperand(line, 1);
    if (!expr || !dest) return;
    const divisor = ctx.evaluate(expr);
    if (!divisor.known) return;
    const recipes = divideRecipes[divisor.value];
    if (!recipes) return;

    // A known dividend is better folded to its quotient than divided.
    if (ctx.registers.knownConstantBefore(index, dest.register) !== undefined)
      return;
    // DIVU.W leaves the remainder in the upper word. The recipes leave junk there.
    if (ctx.registers.upperWordUseAfter(index, dest.register) !== "unused")
      return;
    // Every recipe sets N, Z, V and C differently from DIVU.W. A divide is often
    // followed by a test of the quotient, so this is not guessed at: they must
    // all be proven dead.
    const flags = changedFlagsApplicability(ctx, index, ["N", "Z", "V", "C"]);
    if (flags.applicability !== "safe") return;
    // X is only written by the recipes that shift or add, and DIVU.W leaves it
    // alone. If it is read afterwards those recipes are out; if it is merely
    // not known to be dead (X survives most instructions, so it often is not),
    // they are offered with a warning.
    const xState = ctx.flags.isLiveAfter(index, "X");

    const scratch = ctx.registers
      .deadDataRegistersAfter(index)
      .find((r) => r !== dest.register.toLowerCase());
    // Recipes are ordered from the smallest range to the largest, and the
    // widest is offered first because it assumes the least about the dividend.
    const usable = recipes.filter(
      (r) => (!r.scratch || scratch) && (xState !== "live" || !writesX(r)),
    );
    const widest = usable[usable.length - 1];
    if (!widest) return;
    const narrower = usable.slice(0, -1).reverse();
    const below = (r: DivideRecipe) => `below ${2 ** r.bits}`;

    ctx.report({
      ruleId: this.meta.id,
      category: this.meta.category,
      severity: this.meta.defaultSeverity,
      confidence: "medium",
      message: `DIVU.W #${divisor.value},${dest.register.toUpperCase()} can be a reciprocal multiply if the dividend is ${below(widest)}`,
      loc: line.mnemonic!.loc,
      suggestion: {
        description: `Multiply by the reciprocal of ${divisor.value} (valid for dividends ${below(widest)})`,
        replacement: render(widest, dest.register, scratch),
        applicability: "conditional",
      },
      notes: [
        {
          message: `This is only correct if the dividend in ${dest.register.toUpperCase()} is ${below(widest)}, so its upper word is zero and the quotient cannot overflow. That cannot be proven here; check it.`,
        },
        {
          message:
            "The upper word (DIVU.W's remainder) is provably unused, and N, Z, V and C are dead, so neither the remainder nor the different flag results matter.",
        },
        ...(xState === "unknown" && [widest, ...narrower].some(writesX)
          ? [
              {
                message:
                  "Recipes with shifts or adds also change X, which DIVU.W leaves alone, and nothing here proves X is unused afterwards.",
              },
            ]
          : []),
        ...narrower.map((r) => ({
          message: `If the dividend is ${below(r)}: ${oneLine(render(r, dest.register, scratch))} (${r.cycles} cycles${r.scratch ? `, clobbers ${scratch?.toUpperCase()}` : ""}).`,
        })),
      ],
      data: {
        divisor: divisor.value,
        dividendBelow: 2 ** widest.bits,
        scratch: widest.scratch ? scratch : undefined,
      },
    });
  },
};
